
---
- name: Deploy static HTML website
  hosts: webserver
  become: yes

  tasks:
    - name: Install Nginx web server
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copy HTML file to the web server
      copy:
        src: ../website/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Copy CSS file to the web server
      copy:
        src: ../website/style.css
        dest: /var/www/html/style.css
        owner: www-data
        group: www-data
        mode: '0644'
